---
- hosts: all
  connection: local
  vars:
    cmk_base_api_addr: http://127.0.0.1:5000/monitoring/check_mk/api/1.0
  vars_prompt:
    - name: api_pass
      prompt: provide check_mk 'automation' user credential?
      private: yes
  tasks:
    - name: get host downtimes
      uri:
        url: "{{ cmk_base_api_addr }}/domain-types/downtime/actions/delete/invoke"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer automation {{ api_pass }}"
          Accept: "application/json"
          Content-Type: "application/json"
        body:
          delete_type: "params"
          host_name: "{{ inventory_hostname }}"
        return_content: yes
        status_code: 204
      ignore_errors: yes
      register: resp

    - name: failed while deleting host downtime
      debug:
        msg: "{{ resp.msg }}"
      when: resp.failed

